""""CRIE UM PROGRAMA ONDE O USUARIO POSSA DIGITAR VARIOS VALORES NUMERICOS E CADASTRE-OS EM UMA LISTA.
CASO O NUMERO JA EXISTA LA DENTRO, ELE NAO SERA ADICIONADO. NO FINAL, SERAO EXIBIDOS TODOS OS 
VALORES UNICOS DIGITADOS, EM ORDEM CRESCENTE."""

