""""DESEMVOLVAA UM PROGRAMA QUE LEIA QUATRO VALORES PELO TECLADO E GUARDE-O EM UMA TUPLA
NO FINAL , MOSTRE:

A) QUANTAS VEZES APARECEU O VALOR 9.
B) EM QUE POSICAO FOI DIGITADO O PRIMEIRO VALOR 3.
C) QUAIS FORAM OS NUMERO PARES.
"""