""""CRIE UM PROGRAMA QUE VAI LER VARIOS NUMEROS E COLOCAR EM UMA LISTA. DEPOIS DISSO, CRIE DUAS LISTAS EXTRAS QUE VAO
CONTER APENAS OS VALORES PARES E VALORES IMPARES DIGITADOS, RESPECTIVAMENTE. AO FINAL, MOSTRE O CONTEUDO DAS
TRES LISTAS GERADOS."""

