""""FACA UM PROGRAMA QUE LEIA NOME E PESO DE VARIOAS PESSOAS, GURADANDO TUDO EM UMA LISTA. NO FINAL, MOSTRE:

A) QUANTAS PESSOAS FORAM CADASTRADAS.
B) UMA LISTAGEM COM AS PESSOAS MAIS PESADAS
C) UMA LISTAGEM COM AS PESSOAS MAIS LEVES
"""