""""CRIE UM PROGRAMA QUE LEIA NOME E DUAS NOTAS DE VARIOS ALUNOS E GUARDE TUDO EM UMA LISTA COMPOSTA,
NO FINAL, MOSTRE UM BOLETIM CONTENDO A MEDIA DE CADA UM E PERMITA QUE O USUARIO POSSA MOSTRAR AS  NOTAS DE CADA ALUDO INDIVIDUALMENTE.
 """