""""CRIE UM PROGRAMA QUE VAI LER VARIOS NUMEROS E COLOCAR EM UMA LISTA. DEPOIS
DISSO, MOSTRE:

A) QUANTOS NUMEROS FORAM DIGITADOS.
B) A LISTA DE VALORES, ORDENADA DE FORMA DECRESCENTE.
C) SE O VALOR 5 FOI DIGITADO E ESTA OU NAO NA LISTA."""
