"""EXERCICIO 093: CADASTRO DE JOGADOR DE FUTEBOL

CRIE UM PROGRAMA QUE GERENCIE O APROVEITAMENTO DE UM JOGADOR DE FUTEBOL. O PROGRAMA VAI LER O NOME DE JOGADOR
E QUANTAS PARTIDADS ELE JOGOU. PEDOIS VAI LER A QUANTIDADE DE GOLS FEITOS EM CADA PARTIDA. NO FINAL, TUDO SERA GUARDADO EM UM DICIONARIO, INCLUINDO O TOTAL DE GOLS FEITOS DURANTE O CAMPEONATO.

"""