""""DESENVOLVA UM PROGRAMA QUE LEIA O NOME, IDADE E SEXO DE 4 PESSOAS. NO FINAL DO PROGRAMA, MOSTRE:
A MEDIA DE IDADE DO GRUPO.
QUAL O NOME DO HOMEM MAIS VELHO.
QUANTAS MULHERES TEM MENOS DE 20 ANOS."""
