""""MELHORE O JOGO DO DESAFIO 28 ANDE O COMPUTADOR VAI PENSAR EM UM NUMERO DE 0 A 10. SO QUE AGORA O JOGADOR VAI TENTAR ADIVINHAR ATE ACERTAR O NUMERO QUE O
O COMPUTADOR ESCOLHEU EM QUANTOS PALPITES FOREM NECESSARIOS"""
