""""CRIE UM PROGRAMA QUE LEIA VARIOS NUMEROS INTEIROS PELO TECLADO. O PROGRAMA SO VAI PARAR QUANDO O USUARIO DIGITAR O VALOR 999
QUE É A CONDICAO DE PARADA. NO FINAL, MOSTRE QUANTOS NUMEROS FORAM DIGITADOR E QUAL FOI A SOMA ENTRE ELES
DESCONCIDERANDO O FLOG."""

