""""CRIE UM PROGRAMA QUE LEIA VARIOS NUMERO INTEIROS PELO TECLADO. NO FINAL DA EXECUCAO, MOSTRE A MEDIA
ENTRE TODOS OS VALORES E QUAL FOI O MAIOR E MENOSR VALORE LIDOS. O PROGRAMA DEEVE PERGUNTAR AO USUARIO SE ELE QUER OU NAO
CONTINUAR A DIGITAR VALORES"""

