"""CRIE UM PROGRAMA A IDADE E O SEXO DE VARIAS PESSOAS. A CADA PESSOA CADASTRADA,
O PROGRAMA DEVERA PERGUNTAR SE O USUARIO QUER OU NAO CONTINUAR. NO FIMAL, MOSTRE:
a) QUANTAS PESSOAS TEM MAIS DE 18 ANOS.
b) QUANTOS HOMENSFORAM CADASTRADOS
c) QUANTAS MULHERES TEM ENOS DE 20 ANOS."""