"""CRIE UM PROGRAMA QUE LEIA O NOME E O PRECO DE VARIOS PRODUTOS. O PROGRAMA
DEVERA PERGUNTAR SE O USUARIO VAI CONTINUAR. NO FINAL, MOSTRE:
A) QUAL E O TOTAL GASTO NA COMPRA
B) QUANTOS PRODUTOS CUSTAM MAIS DE R$1000
C) QUAL 'E O PRODUTO MAIS BARATOI"""