"""CRIE UM PROGRAMA QUE SIMULE O FUNCIONAMENTO DE UM CAIXA ELETRONICO. NO INICIO, PERGUNTE AO
USUARIO QUAL SERA O VALOR A SER SACADO (NUMERO INTEIRO) E O PROGRAMA VAI INFORMAR QUANTAS CEDULAS DE CADA VALOR SERAO ENTREGUES
OBS; CONSIDERE QUE O CAIXA POSSUI CEDULAS DE R$ 50, 20, 10 E 1"""
